plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

version = "0.0.1"
group = "com.lycanite.core"

base {
    archivesName = "lycanitesmobs"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()

    maven {
        url = "https://api.modrinth.com/maven"
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

neoForge {
    version = neo_version

    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = parchment_minecraft_version
    }

    runs {

        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'forge.logging.markers', 'REGISTRIES'
        }

        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            data()

            programArguments.addAll(
                    '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources').absolutePath,
                    '--existing', file('src/main/resources').absolutePath
            )
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {

    implementation "maven.modrinth:sodium:mc1.21.1-0.6.13-neoforge"

}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {

    var replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            loader_version_range    : loader_version_range,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description         : mod_description
    ]

    inputs.properties replaceProperties

    expand replaceProperties

    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata

publishing {

    publications {

        register('mavenJava', MavenPublication) {
            from components.java
        }
    }

    repositories {

        maven {
            url = layout.projectDirectory.dir("repo")
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ProcessResources).configureEach {
    includeEmptyDirs = false
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/java/common') {
        into 'common/lycanitesmobs'
        exclude 'lycanitesmobs/**'
        include '**'
    }
    from('src/main/java/common/lycanitesmobs') {
        into 'common/lycanitesmobs'
        include '**'
    }
}

var copyPrecompiledClasses = tasks.register('copyPrecompiledClasses', Sync) {
    from('src/main/java/com') {
        include '**/*.class'
        eachFile { details ->
            details.path = "com/lycanitesmobs/${details.path}"
        }
        includeEmptyDirs = false
    }
    into layout.buildDirectory.dir('classes/java/main')
}

tasks.named('classes').configure {
    dependsOn copyPrecompiledClasses
}

tasks.named('jar', Jar).configure {
    dependsOn copyPrecompiledClasses
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

idea {

    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
