modLoader="javafml"
loaderVersion="[4,)"
license="GPLv3"

[[mods]]
modId="lycanitesmobs"
version="0.0.1"
displayName="Lycanites Mobs Reloaded"
authors="Lycanite"
description='''
Lycanites Mobs Reloaded for NeoForge 1.21.1
'''
[[dependencies.lycanitesmobs]]
modId="sodium"
type="required"
versionRange="[0.6.13,)"
ordering="NONE"
side="CLIENT"

[[dependencies.lycanitesmobs]]
modId="neoforge"
type="required"
versionRange="[21.1.231,)"
ordering="NONE"
side="BOTH"

[[dependencies.lycanitesmobs]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
